# Generated by Django 6.1.1 on 2026-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=30)),
                ('year_level', models.IntegerField(default=1)),
                ('section', models.CharField(max_length=20)),
            ],
        ),
    ]
